### PR TITLE
Fix naming in POI APIs

### PR DESCRIPTION
**Pull request by anthonyroux**

### CODE REVIEW

**Comment by anthonyroux** [comment]
@akshitsingla as we were struggling to understand each other on the naming I made a PR on your branch with the updates. I let you review it and come back with any questions you might have.

**Comment by anthonyroux** [comment]
PS: not linked to this PR but the code coverage can be improved:
image

**Comment by akshitsingla** [comment]
Ah, I see what you're proposing - but it's not possible from a technical standpoint.
__Detail__: AFAIK, it's not possible to have the same variable as an *object* as well as a *function* in javascript.
Hence, we can not have both `pointsOfInterest` as well as `pointsOfInterest()` co-exist.

**Comment by akshitsingla** [comment]
Hence, you see the same work-around in __Airport & City Search API__ as well:
image

**Comment by akshitsingla** [comment]
> PS: not linked to this PR but the code coverage can be improved:
> image

Deserves its own *issue*?

**Comment by anthonyroux** [comment]
I am confused I do not use the same do I? 
**In English** the singular version is: point of interest (no s at point not s at interest).
**In English** the plurial version is: point**s** of interest (s only at the word _point_ not at the word _interest_).

**In our API**:
2 endpoints to search for multiple points of interest (s at the word _points_):
-  amadeus.referenceData.locations.pointsOfInterest.get({...})
- amadeus.referenceData.locations.pointsOfInterest.bySquare.get({...})

1 endpoint to retrieve one specific point of interest (no s):
- amadeus.referenceData.locations.pointOfInterest('9CB40CB5D0').get()


**Airport & City Search**:
Retrieve many airports/cities (s at _locations_)
- amadeus.referenceData.locations.get({...})

Retrieve a single airport or city by its id (no s at _location_):
- amadeus.referenceData.location('ALHR').get()

------
I have tested this PR on a sample code and it works fine.

**Comment by akshitsingla** [comment]
OMG! I think I got it!
I have been talking about the "s" at the end of "interest", while you have been talking about "s" at the end of "point"!!!
Am I right? 

So, the final signatures should look like this:
- amadeus.referenceData.locations.pointsOfInterest.get({...})
- amadeus.referenceData.locations.pointsOfInterest.bySquare.get({...})
- amadeus.referenceData.locations.pointsOfInterest('9CB40CB5D0').get()

Correct?

**Comment by anthonyroux** [comment]
Yes, there is no s at the end of interest. 

If if it is ok for you you can approve/merge this PR on your branch and open a PR from `pois` to `master`.

**Comment by anthonyroux** [comment]
Actually I just realized that you did again the same mistake in the endpoints:
image

If you read the code of my PR or the explanation I put before:
image

**Comment by akshitsingla** [comment]
Yes yes, that comment was made before our meeting.
All is clear now, I'm going to merge this PR with your changes.

**Pull request merged**
